name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    # TODO: also use ARM paramaters
    # TODO: resource names should be paramaterised
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 3.1.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Restore dependencies
      working-directory: Functions/
      run: dotnet restore

    - name: Build
      working-directory: Functions/
      run: dotnet build --no-restore

    - name: Deploy
      working-directory: Functions/
      run: dotnet publish
        --configuration Release
        --output ../deploy

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.1
      with:
        name: functionsapp
        path: deploy

  validate-resources:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 5.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Generate ARM Template
      working-directory: Azure/
      run: dotnet run
      env:
          AUTH0_AUDIENCE: ${{ secrets.AUTH0_AUDIENCE }}
          AUTH0_ISSUER: ${{ secrets.AUTH0_ISSUER }}

    - name: Login with Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Run ARM deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: Azure/arm-template.json
        deploymentMode: Validate

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.1
      with:
        name: arm-template
        path: Azure/arm-template.json

  deploy:
    needs: [build, validate-resources]
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: arm-template

    - name: Login with Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Run ARM deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: Azure/arm-template.json

    - name: Setup .NET 3.1.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Login with Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - uses: actions/download-artifact@v2
      with:
        name: functionsapp
        path: deploy

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: sswrules-functions-staging
        package: deploy